
{ ... }:

{
  imports = [
    ./leenix.nix
    ./leenix-ac-present.nix
    ./leenix-audio-input-mute.nix
    ./leenix-audio-output-switch.nix
    ./leenix-battery-capacity.nix
    ./leenix-battery-monitor.nix
    ./leenix-battery-present.nix
    ./leenix-battery-remaining.nix
    ./leenix-battery-remaining-time.nix
    ./leenix-battery-status.nix
    ./leenix-branch-set.nix
    ./leenix-branding-about.nix
    ./leenix-branding-screensaver.nix
    ./leenix-brightness-display.nix
    ./leenix-brightness-display-apple.nix
    ./leenix-brightness-keyboard.nix
    ./leenix-brightness-keyboard-mute.nix
    ./leenix-capture-screenrecording.nix
    ./leenix-capture-screenshot.nix
    ./leenix-capture-text-extraction.nix
    ./leenix-channel-set.nix
    ./leenix-cmd-missing.nix
    ./leenix-cmd-present.nix
    ./leenix-cmd-terminal-cwd.nix
    ./leenix-config-direct-boot.nix
    ./leenix-debug.nix
    ./leenix-default-browser.nix
    ./leenix-default-editor.nix
    ./leenix-default-terminal.nix
    ./leenix-dev-add-migration.nix
    ./leenix-dev-benchmark.nix
    ./leenix-dev-bin-metadata.nix
    ./leenix-drive-info.nix
    ./leenix-drive-password.nix
    ./leenix-drive-select.nix
    ./leenix-first-run.nix
    ./leenix-font-current.nix
    ./leenix-font-list.nix
    ./leenix-font-set.nix
    ./leenix-hibernation-available.nix
    ./leenix-hibernation-remove.nix
    ./leenix-hibernation-setup.nix
    ./leenix-hook.nix
    ./leenix-hook-install.nix
    ./leenix-hw-asus-expertbook-b9406.nix
    ./leenix-hw-asus-rog.nix
    ./leenix-hw-asus-zenbook-ux5406aa.nix
    ./leenix-hw-dell-xps-haptic-touchpad.nix
    ./leenix-hw-dell-xps-oled.nix
    ./leenix-hw-external-monitors.nix
    ./leenix-hw-framework16.nix
    ./leenix-hw-hybrid-gpu.nix
    ./leenix-hw-intel.nix
    ./leenix-hw-intel-ptl.nix
    ./leenix-hw-intel-sof.nix
    ./leenix-hw-match.nix
    ./leenix-hw-nvidia-gsp.nix
    ./leenix-hw-nvidia-without-gsp.nix
    ./leenix-hw-recover-internal-monitor.nix
    ./leenix-hw-surface.nix
    ./leenix-hw-touchpad.nix
    ./leenix-hw-touchscreen.nix
    ./leenix-hw-vulkan.nix
    ./leenix-hyprland-monitor-focused.nix
    ./leenix-hyprland-monitor-focused-apple.nix
    ./leenix-hyprland-monitor-internal.nix
    ./leenix-hyprland-monitor-internal-mirror.nix
    ./leenix-hyprland-monitor-scaling-cycle.nix
    ./leenix-hyprland-monitor-watch.nix
    ./leenix-hyprland-toggle.nix
    ./leenix-hyprland-toggle-disabled.nix
    ./leenix-hyprland-toggle-enabled.nix
    ./leenix-hyprland-window-close-all.nix
    ./leenix-hyprland-window-gaps-toggle.nix
    ./leenix-hyprland-window-pop.nix
    ./leenix-hyprland-window-single-square-aspect-toggle.nix
    ./leenix-hyprland-window-transparency-toggle.nix
    ./leenix-hyprland-workspace-layout-toggle.nix
    ./leenix-install-browser.nix
    ./leenix-install-chromium-google-account.nix
    ./leenix-install-dev-env.nix
    ./leenix-install-docker-dbs.nix
    ./leenix-install-dropbox.nix
    ./leenix-install-gaming-geforce-now.nix
    ./leenix-install-gaming-gpu-lib32.nix
    ./leenix-install-gaming-heroic.nix
    ./leenix-install-gaming-lutris.nix
    ./leenix-install-gaming-moonlight.nix
    ./leenix-install-gaming-retroarch.nix
    ./leenix-install-gaming-steam.nix
    ./leenix-install-gaming-xbox-cloud.nix
    ./leenix-install-gaming-xbox-controllers.nix
    ./leenix-install-helix.nix
    ./leenix-install-nordvpn.nix
    ./leenix-install-once.nix
    ./leenix-install-tailscale.nix
    ./leenix-install-terminal.nix
    ./leenix-install-vscode.nix
    ./leenix-install-zed.nix
    ./leenix-launch-about.nix
    ./leenix-launch-audio.nix
    ./leenix-launch-bluetooth.nix
    ./leenix-launch-browser.nix
    ./leenix-launch-editor.nix
    ./leenix-launch-floating-terminal-with-presentation.nix
    ./leenix-launch-or-focus.nix
    ./leenix-launch-or-focus-tui.nix
    ./leenix-launch-or-focus-webapp.nix
    ./leenix-launch-screensaver.nix
    ./leenix-launch-tui.nix
    ./leenix-launch-walker.nix
    ./leenix-launch-webapp.nix
    ./leenix-launch-wifi.nix
    ./leenix-menu.nix
    ./leenix-menu-file.nix
    ./leenix-menu-input.nix
    ./leenix-menu-keybindings.nix
    ./leenix-menu-select.nix
    ./leenix-menu-share.nix
    ./leenix-migrate.nix
    ./leenix-notification-dismiss.nix
    ./leenix-notification-send.nix
    ./leenix-npx-install.nix
    ./leenix-pkg-add.nix
    ./leenix-pkg-aur-accessible.nix
    ./leenix-pkg-aur-add.nix
    ./leenix-pkg-aur-install.nix
    ./leenix-pkg-drop.nix
    ./leenix-pkg-install.nix
    ./leenix-pkg-missing.nix
    ./leenix-pkg-present.nix
    ./leenix-pkg-remove.nix
    ./leenix-plymouth-preview.nix
    ./leenix-plymouth-reset.nix
    ./leenix-plymouth-set.nix
    ./leenix-plymouth-set-by-theme.nix
    ./leenix-powerprofiles-init.nix
    ./leenix-powerprofiles-list.nix
    ./leenix-powerprofiles-set.nix
    ./leenix-refresh-applications.nix
    ./leenix-refresh-chromium.nix
    ./leenix-refresh-config.nix
    ./leenix-refresh-fastfetch.nix
    ./leenix-refresh-hypridle.nix
    ./leenix-refresh-hyprland.nix
    ./leenix-refresh-hyprlock.nix
    ./leenix-refresh-hyprsunset.nix
    ./leenix-refresh-limine.nix
    ./leenix-refresh-pacman.nix
    ./leenix-refresh-plymouth.nix
    ./leenix-refresh-sddm.nix
    ./leenix-refresh-swayosd.nix
    ./leenix-refresh-tmux.nix
    ./leenix-refresh-walker.nix
    ./leenix-refresh-waybar.nix
    ./leenix-reinstall.nix
    ./leenix-reinstall-configs.nix
    ./leenix-reinstall-git.nix
    ./leenix-reinstall-pkgs.nix
    ./leenix-reminder.nix
    ./leenix-remove-browser.nix
    ./leenix-remove-dev-env.nix
    ./leenix-remove-gaming-geforce-now.nix
    ./leenix-remove-gaming-heroic.nix
    ./leenix-remove-gaming-lutris.nix
    ./leenix-remove-gaming-minecraft.nix
    ./leenix-remove-gaming-moonlight.nix
    ./leenix-remove-gaming-retroarch.nix
    ./leenix-remove-gaming-steam.nix
    ./leenix-remove-gaming-xbox-cloud.nix
    ./leenix-remove-gaming-xbox-controllers.nix
    ./leenix-remove-preinstalls.nix
    ./leenix-remove-security-fido2.nix
    ./leenix-remove-security-fingerprint.nix
    ./leenix-restart-app.nix
    ./leenix-restart-bluetooth.nix
    ./leenix-restart-btop.nix
    ./leenix-restart-helix.nix
    ./leenix-restart-hyprctl.nix
    ./leenix-restart-hypridle.nix
    ./leenix-restart-hyprsunset.nix
    ./leenix-restart-mako.nix
    ./leenix-restart-opencode.nix
    ./leenix-restart-pipewire.nix
    ./leenix-restart-swayosd.nix
    ./leenix-restart-terminal.nix
    ./leenix-restart-tmux.nix
    ./leenix-restart-trackpad.nix
    ./leenix-restart-walker.nix
    ./leenix-restart-waybar.nix
    ./leenix-restart-wifi.nix
    ./leenix-restart-xcompose.nix
    ./leenix-screensaver.nix
    ./leenix-setup-dns.nix
    ./leenix-setup-security-fido2.nix
    ./leenix-setup-security-fingerprint.nix
    ./leenix-show-done.nix
    ./leenix-show-logo.nix
    ./leenix-snapshot.nix
    ./leenix-state.nix
    ./leenix-sudo-keepalive.nix
    ./leenix-sudo-passwordless.nix
    ./leenix-sudo-reset.nix
    ./leenix-swayosd-brightness.nix
    ./leenix-swayosd-client.nix
    ./leenix-swayosd-kbd-brightness.nix
    ./leenix-system-lock.nix
    ./leenix-system-logout.nix
    ./leenix-system-reboot.nix
    ./leenix-system-shutdown.nix
    ./leenix-system-wake.nix
    ./leenix-theme-bg-install.nix
    ./leenix-theme-bg-next.nix
    ./leenix-theme-bg-set.nix
    ./leenix-theme-colors-from-alacritty.nix
    ./leenix-theme-current.nix
    ./leenix-theme-install.nix
    ./leenix-theme-list.nix
    ./leenix-theme-refresh.nix
    ./leenix-theme-remove.nix
    ./leenix-theme-set.nix
    ./leenix-theme-set-browser.nix
    ./leenix-theme-set-foot.nix
    ./leenix-theme-set-gnome.nix
    ./leenix-theme-set-keyboard.nix
    ./leenix-theme-set-keyboard-asus-rog.nix
    ./leenix-theme-set-keyboard-f16.nix
    ./leenix-theme-set-obsidian.nix
    ./leenix-theme-set-templates.nix
    ./leenix-theme-set-vscode.nix
    ./leenix-theme-update.nix
    ./leenix-toggle.nix
    ./leenix-toggle-enabled.nix
    ./leenix-toggle-hybrid-gpu.nix
    ./leenix-toggle-idle.nix
    ./leenix-toggle-nightlight.nix
    ./leenix-toggle-notification-silencing.nix
    ./leenix-toggle-screensaver.nix
    ./leenix-toggle-suspend.nix
    ./leenix-toggle-touchpad.nix
    ./leenix-toggle-touchscreen.nix
    ./leenix-toggle-waybar.nix
    ./leenix-transcode.nix
    ./leenix-transcode-ascii.nix
    ./leenix-tui-install.nix
    ./leenix-tui-remove.nix
    ./leenix-tui-remove-all.nix
    ./leenix-tz-select.nix
    ./leenix-update.nix
    ./leenix-update-analyze-logs.nix
    ./leenix-update-aur-pkgs.nix
    ./leenix-update-available.nix
    ./leenix-update-available-reset.nix
    ./leenix-update-branch.nix
    ./leenix-update-confirm.nix
    ./leenix-update-firmware.nix
    ./leenix-update-git.nix
    ./leenix-update-keyring.nix
    ./leenix-update-orphan-pkgs.nix
    ./leenix-update-perform.nix
    ./leenix-update-restart.nix
    ./leenix-update-system-pkgs.nix
    ./leenix-update-time.nix
    ./leenix-update-without-idle.nix
    ./leenix-upload-log.nix
    ./leenix-version.nix
    ./leenix-version-branch.nix
    ./leenix-version-channel.nix
    ./leenix-version-pkgs.nix
    ./leenix-voxtype-config.nix
    ./leenix-voxtype-install.nix
    ./leenix-voxtype-model.nix
    ./leenix-voxtype-remove.nix
    ./leenix-voxtype-status.nix
    ./leenix-weather-icon.nix
    ./leenix-weather-status.nix
    ./leenix-webapp-handler-hey.nix
    ./leenix-webapp-handler-zoom.nix
    ./leenix-webapp-install.nix
    ./leenix-webapp-remove.nix
    ./leenix-webapp-remove-all.nix
    ./leenix-wifi-powersave.nix
    ./leenix-windows-vm.nix
  ];

}
