{
  pkgs,
  ...
}:

{
  home.packages = [
    (pkgs.writeShellApplication {
      name = "leenix-hyprmon-edit";
      excludeShellChecks = [ "SC2086" ];

      runtimeInputs = with pkgs; [
        coreutils
        gawk
      ];

      text = ''
        #!/bin/bash

        # leenix:summary=Single canonical LEENIX writer for ~/.config/hypr/hyprmon.lua (flock-protected)

        # leenix:args=<set <monitor> <true|false>|mirror <target> <source>|unmirror <target>>

        # Every LEENIX-side PERSISTENT change to HyprMon's hyprmon.lua goes
        # through this command. It:
        #   1. acquires an exclusive flock on a lock file under
        #      ''${XDG_RUNTIME_DIR:-$XDG_STATE_HOME}/leenix (advisory among LEENIX
        #      writers; HyprMon's own TUI does not flock but always rewrites
        #      from live state and keeps backups),
        #   2. re-reads the LATEST hyprmon.lua only after holding the lock,
        #   3. applies the smallest possible transformation (only the matching
        #      monitor's line; unrelated HyprMon fields are never touched),
        #   4. atomically replaces the file (tmp + mv).
        #
        # The reconciliation daemon (leenix-monitor reconcile) NEVER calls this:
        # temporary safety overrides are applied via `hyprctl eval` only and are
        # never persisted.

        set -euo pipefail

        HYPRMON_LUA="''${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprmon.lua"
        LOCK_ROOT="''${XDG_RUNTIME_DIR:-''${XDG_STATE_HOME:-$HOME/.local/state}}/leenix"
        LOCKFILE="$LOCK_ROOT/hyprmon.lua.lock"

        cmd="''${1:-}"
        case "$cmd" in
          set)
            [[ -n ''${2:-} && -n ''${3:-} ]] || { echo "usage: leenix-hyprmon-edit set <monitor> <true|false>" >&2; exit 1; }
            ;;
          mirror)
            [[ -n ''${2:-} && -n ''${3:-} ]] || { echo "usage: leenix-hyprmon-edit mirror <target> <source>" >&2; exit 1; }
            ;;
          unmirror)
            [[ -n ''${2:-} ]] || { echo "usage: leenix-hyprmon-edit unmirror <target>" >&2; exit 1; }
            ;;
          *)
            echo "usage: leenix-hyprmon-edit <set <mon> <true|false>|mirror <target> <source>|unmirror <target>>" >&2
            exit 1
            ;;
        esac

        mkdir -p "$(dirname "$LOCKFILE")" "$(dirname "$HYPRMON_LUA")"

        (
          flock 9

          # Re-read only now, under the lock.
          [[ -f $HYPRMON_LUA ]] || printf '%s\n' "-- Generated by HyprMon. Manual changes may be overwritten." "" > "$HYPRMON_LUA"

          case "$cmd" in
            set)
              mon="''${2:-}" state="''${3:-}"
              if grep -qF "output = \"$mon\"" "$HYPRMON_LUA"; then
                tmp="$HYPRMON_LUA.tmp.$$"
                awk -v mon="$mon" -v state="$state" '
                  index($0, "output = \"" mon "\"") > 0 {
                    line = $0
                    if (line ~ /disabled = true/)  { gsub(/disabled = true/,  "disabled = " state, line) }
                    else if (line ~ /disabled = false/) { gsub(/disabled = false/, "disabled = " state, line) }
                    else { sub(/ ?\}\)$/, ", disabled = " state " })", line) }
                    print line
                    next
                  }
                  { print }
                ' "$HYPRMON_LUA" > "$tmp"
                mv -f "$tmp" "$HYPRMON_LUA"
              else
                printf '%s\n' "hl.monitor({ output = \"$mon\", disabled = $state })" >> "$HYPRMON_LUA"
              fi
              ;;
            mirror)
              target="''${2:-}" source="''${3:-}"
              if grep -qF "output = \"$target\"" "$HYPRMON_LUA"; then
                tmp="$HYPRMON_LUA.tmp.$$"
                awk -v t="$target" -v s="$source" '
                  index($0, "output = \"" t "\"") > 0 {
                    line = $0
                    sub(/, mirror = "[^"]*"/, "", line)
                    if (line ~ /disabled = true/)  { sub(/disabled = true/,  "disabled = false", line) }
                    else if (line !~ /disabled = false/) { sub(/ ?\}\)$/, ", disabled = false", line) }
                    sub(/ ?\}\)$/, ", mirror = \"" s "\" })", line)
                    print line
                    next
                  }
                  { print }
                ' "$HYPRMON_LUA" > "$tmp"
                mv -f "$tmp" "$HYPRMON_LUA"
              else
                printf '%s\n' "hl.monitor({ output = \"$target\", disabled = false, mirror = \"$source\" })" >> "$HYPRMON_LUA"
              fi
              ;;
            unmirror)
              target="''${2:-}"
              [[ -f $HYPRMON_LUA ]] || exit 0
              if grep -qF "output = \"$target\"" "$HYPRMON_LUA"; then
                tmp="$HYPRMON_LUA.tmp.$$"
                awk -v t="$target" '
                  index($0, "output = \"" t "\"") > 0 {
                    line = $0
                    sub(/, mirror = "[^"]*"/, "", line)
                    if (line !~ /disabled =/) { sub(/ ?\}\)$/, ", disabled = false", line) }
                    print line
                    next
                  }
                  { print }
                ' "$HYPRMON_LUA" > "$tmp"
                mv -f "$tmp" "$HYPRMON_LUA"
              fi
              ;;
          esac
        ) 9>"$LOCKFILE"
      '';
    })
  ];
}
