{ ... }:

{
  imports = [
    ./leenix-branch-set.nix
    ./leenix-branding-about.nix
    ./leenix-branding-screensaver.nix
    ./leenix-channel-set.nix
    ./leenix-debug.nix
    ./leenix-hibernation-available.nix
    ./leenix-hibernation-remove.nix
    ./leenix-hibernation-setup.nix
    ./leenix-hyprland-toggle.nix
    ./leenix-install-browser.nix
    ./leenix-install-dropbox.nix
    ./leenix-install-gaming-gpu-lib32.nix
    ./leenix-install-gaming-heroic.nix
    ./leenix-install-gaming-moonlight.nix
    ./leenix-install-gaming-retroarch.nix
    ./leenix-install-gaming-steam.nix
    ./leenix-install-helix.nix
    ./leenix-install-nordvpn.nix
    ./leenix-install-terminal.nix
    ./leenix-launch-screensaver.nix
    ./leenix-migrate.nix
    ./leenix-pkg-add.nix
    ./leenix-pkg-aur-accessible.nix
    ./leenix-pkg-aur-add.nix
    ./leenix-pkg-aur-install.nix
    ./leenix-pkg-drop.nix
    ./leenix-pkg-install.nix
    ./leenix-pkg-missing.nix
    ./leenix-pkg-present.nix
    ./leenix-pkg-remove.nix
    ./leenix-plymouth-preview.nix
    ./leenix-plymouth-reset.nix
    ./leenix-plymouth-set.nix
    ./leenix-plymouth-set-by-theme.nix
    ./leenix-refresh-applications.nix
    ./leenix-refresh-chromium.nix
    ./leenix-refresh-config.nix
    ./leenix-refresh-fastfetch.nix
    ./leenix-refresh-hypridle.nix
    ./leenix-refresh-hyprland.nix
    ./leenix-refresh-hyprlock.nix
    ./leenix-refresh-hyprsunset.nix
    ./leenix-refresh-limine.nix
    ./leenix-refresh-pacman.nix
    ./leenix-refresh-plymouth.nix
    ./leenix-refresh-sddm.nix
    ./leenix-refresh-swayosd.nix
    ./leenix-refresh-tmux.nix
    ./leenix-refresh-walker.nix
    ./leenix-refresh-waybar.nix
    ./leenix-reinstall.nix
    ./leenix-reinstall-configs.nix
    ./leenix-reinstall-git.nix
    ./leenix-reinstall-pkgs.nix
    ./leenix-remove-dev-env.nix
    ./leenix-remove-gaming-heroic.nix
    ./leenix-remove-gaming-lutris.nix
    ./leenix-remove-gaming-minecraft.nix
    ./leenix-remove-gaming-moonlight.nix
    ./leenix-remove-gaming-retroarch.nix
    ./leenix-remove-gaming-steam.nix
    ./leenix-remove-preinstalls.nix
    ./leenix-snapshot.nix
    ./leenix-theme-list.nix
    ./leenix-theme-set.nix
    ./leenix-theme-set-templates.nix
    ./leenix-update.nix
    ./leenix-update-analyze-logs.nix
    ./leenix-update-aur-pkgs.nix
    ./leenix-update-available.nix
    ./leenix-update-branch.nix
    ./leenix-update-confirm.nix
    ./leenix-update-git.nix
    ./leenix-update-keyring.nix
    ./leenix-update-orphan-pkgs.nix
    ./leenix-update-perform.nix
    ./leenix-update-restart.nix
    ./leenix-update-system-pkgs.nix
    ./leenix-upload-log.nix
    ./leenix-version.nix
    ./leenix-version-branch.nix
    ./leenix-version-channel.nix
    ./leenix-version-pkgs.nix
    ./leenix-voxtype-install.nix
    ./leenix-voxtype-remove.nix
  ];
}
