{ ... }:

{
  imports = [
    ./leenix-ac-present.nix
    ./leenix-audio-input-mute.nix
    ./leenix-audio-output-switch.nix
    ./leenix-battery-capacity.nix
    ./leenix-battery-monitor.nix
    ./leenix-battery-present.nix
    ./leenix-battery-remaining.nix
    ./leenix-battery-remaining-time.nix
    ./leenix-battery-status.nix
    ./leenix-brightness-display.nix
    ./leenix-brightness-keyboard.nix
    ./leenix-brightness-keyboard-mute.nix
    ./leenix-branding-screensaver.nix
    ./leenix-capture-screenrecording.nix
    ./leenix-capture-screenshot.nix
    ./leenix-capture-text-extraction.nix
    ./leenix-cmd-missing.nix
    ./leenix-cmd-present.nix
    ./leenix-cmd-terminal-cwd.nix
    ./leenix-default-terminal.nix
    ./leenix-dev-add-migration.nix
    ./leenix-dev-benchmark.nix
    ./leenix-dev-bin-metadata.nix
    ./leenix-drive-info.nix
    ./leenix-drive-select.nix
    ./leenix-font-current.nix
    ./leenix-font-list.nix
    ./leenix-font-set.nix
    ./leenix-hook.nix
    ./leenix-hook-install.nix
    ./leenix-hw-asus-expertbook-b9406.nix
    ./leenix-hw-asus-rog.nix
    ./leenix-hw-asus-zenbook-ux5406aa.nix
    ./leenix-hw-dell-xps-haptic-touchpad.nix
    ./leenix-hw-dell-xps-oled.nix
    ./leenix-hw-external-monitors.nix
    ./leenix-hw-framework16.nix
    ./leenix-hw-hybrid-gpu.nix
    ./leenix-hw-intel.nix
    ./leenix-hw-intel-ptl.nix
    ./leenix-hw-intel-sof.nix
    ./leenix-hw-match.nix
    ./leenix-hw-nvidia-gsp.nix
    ./leenix-hw-nvidia-without-gsp.nix
    ./leenix-hw-recover-internal-monitor.nix
    ./leenix-hw-surface.nix
    ./leenix-hw-touchpad.nix
    ./leenix-hw-touchscreen.nix
    ./leenix-hw-vulkan.nix
    ./leenix-hypr-zoom.nix
    ./leenix-hyprland-monitor-focused.nix
    ./leenix-hyprland-monitor-focused-apple.nix
    ./leenix-hyprland-monitor-internal.nix
    ./leenix-hyprland-monitor-internal-mirror.nix
    ./leenix-hyprland-monitor-scaling-cycle.nix
    ./leenix-hyprland-monitor-watch.nix
    ./leenix-hyprland-toggle-disabled.nix
    ./leenix-hyprland-toggle-enabled.nix
    ./leenix-hyprland-window-close-all.nix
    ./leenix-hyprland-window-gaps-toggle.nix
    ./leenix-hyprland-window-pop.nix
    ./leenix-hyprland-window-single-square-aspect-toggle.nix
    ./leenix-hyprland-window-transparency-toggle.nix
    ./leenix-hyprland-workspace-layout-toggle.nix
    ./leenix-install-chromium-google-account.nix
    ./leenix-install-gaming-geforce-now.nix
    ./leenix-install-gaming-xbox-cloud.nix
    ./leenix-install-vscode.nix
    ./leenix-install-zed.nix
    ./leenix-launch-about.nix
    ./leenix-launch-audio.nix
    ./leenix-launch-bluetooth.nix
    ./leenix-launch-screensaver.nix
    ./leenix-launch-wifi.nix
    ./leenix-menu.nix
    ./leenix-menu-share.nix
    ./leenix-notification-dismiss.nix
    ./leenix-notification-send.nix
    ./leenix-npx-install.nix
    ./leenix-powerprofiles-init.nix
    ./leenix-powerprofiles-list.nix
    ./leenix-powerprofiles-set.nix
    ./leenix-reminder.nix
    ./leenix-remove-gaming-geforce-now.nix
    ./leenix-remove-gaming-xbox-cloud.nix
    ./leenix-restart-bluetooth.nix
    ./leenix-restart-btop.nix
    ./leenix-restart-helix.nix
    ./leenix-restart-hyprctl.nix
    ./leenix-restart-hypridle.nix
    ./leenix-restart-hyprsunset.nix
    ./leenix-restart-mako.nix
    ./leenix-restart-opencode.nix
    ./leenix-restart-pipewire.nix
    ./leenix-restart-swayosd.nix
    ./leenix-restart-terminal.nix
    ./leenix-restart-tmux.nix
    ./leenix-restart-wifi.nix
    ./leenix-restart-xcompose.nix
    ./leenix-screensaver.nix
    ./leenix-show-done.nix
    ./leenix-show-logo.nix
    ./leenix-state.nix
    ./leenix-swayosd-brightness.nix
    ./leenix-swayosd-client.nix
    ./leenix-swayosd-kbd-brightness.nix
    ./leenix-system-lock.nix
    ./leenix-system-reboot.nix
    ./leenix-system-shutdown.nix
    ./leenix-system-wake.nix
    ./leenix-theme-colors-from-alacritty.nix
    ./leenix-theme-current.nix
    ./leenix-theme-install.nix
    ./leenix-theme-refresh.nix
    ./leenix-theme-remove.nix
    ./leenix-theme-set-foot.nix
    ./leenix-theme-set-gnome.nix
    ./leenix-theme-set-keyboard.nix
    ./leenix-theme-set-keyboard-asus-rog.nix
    ./leenix-theme-set-keyboard-f16.nix
    ./leenix-theme-set-obsidian.nix
    ./leenix-theme-set-vscode.nix
    ./leenix-theme-update.nix
    ./leenix-toggle.nix
    ./leenix-toggle-enabled.nix
    ./leenix-toggle-notification-silencing.nix
    ./leenix-toggle-screensaver.nix
    ./leenix-toggle-suspend.nix
    ./leenix-toggle-touchpad.nix
    ./leenix-toggle-touchscreen.nix
    ./leenix-tz-select.nix
    ./leenix-transcode.nix
    ./leenix-transcode-ascii.nix
    ./leenix-tui-install.nix
    ./leenix-tui-remove.nix
    ./leenix-tui-remove-all.nix
    ./leenix-update-available-reset.nix
    ./leenix-update-without-idle.nix
    ./leenix-voxtype-config.nix
    ./leenix-voxtype-model.nix
    ./leenix-voxtype-status.nix
    ./leenix-weather-data.nix
    ./leenix-weather-icon.nix
    ./leenix-weather-status.nix
    ./leenix-wifi-powersave.nix
  ];
}
