{ ... }:

{
  wayland.windowManager.hyprland.settings = {
    env = [
      # Gum Style
      "FOREGROUND,##d8e3e0"
      "BACKGROUND,##0b1113"
      "BORDER_FOREGROUND,##33b8a8"
      "BORDER_BACKGROUND,##0b1113"

      # Gum Confirm Style
      "GUM_CONFIRM_PROMPT_FOREGROUND,##33b8a8"
      "GUM_CONFIRM_PROMPT_BACKGROUND,##0b1113"
      "GUM_CONFIRM_SELECTED_FOREGROUND,##f2f8f6"
      "GUM_CONFIRM_SELECTED_BACKGROUND,##365156"
      "GUM_CONFIRM_UNSELECTED_FOREGROUND,##d8e3e0"
      "GUM_CONFIRM_UNSELECTED_BACKGROUND,##0b1113"

      # Gum Input Style
      "GUM_INPUT_PROMPT_FOREGROUND,##33b8a8"
      "GUM_INPUT_PROMPT_BACKGROUND,##0b1113"
      "GUM_INPUT_PLACEHOLDER_FOREGROUND,##4a5f62"
      "GUM_INPUT_PLACEHOLDER_BACKGROUND,##0b1113"
      "GUM_INPUT_CURSOR_FOREGROUND,##d8e3e0"
      "GUM_INPUT_CURSOR_BACKGROUND,##0b1113"
      "GUM_INPUT_HEADER_FOREGROUND,##d8e3e0"
      "GUM_INPUT_HEADER_BACKGROUND,##0b1113"

      # Gum Choose Style
      "GUM_CHOOSE_CURSOR_FOREGROUND,##33b8a8"
      "GUM_CHOOSE_CURSOR_BACKGROUND,##0b1113"
      "GUM_CHOOSE_HEADER_FOREGROUND,##d8e3e0"
      "GUM_CHOOSE_HEADER_BACKGROUND,##0b1113"
      "GUM_CHOOSE_ITEM_FOREGROUND,##d8e3e0"
      "GUM_CHOOSE_ITEM_BACKGROUND,##0b1113"
      "GUM_CHOOSE_SELECTED_FOREGROUND,##f2f8f6"
      "GUM_CHOOSE_SELECTED_BACKGROUND,##365156"

      # Gum Filter Style
      "GUM_FILTER_PROMPT_FOREGROUND,##33b8a8"
      "GUM_FILTER_PROMPT_BACKGROUND,##0b1113"
      "GUM_FILTER_TEXT_FOREGROUND,##d8e3e0"
      "GUM_FILTER_TEXT_BACKGROUND,##0b1113"
      "GUM_FILTER_MATCH_FOREGROUND,##33b8a8"
      "GUM_FILTER_CURSOR_TEXT_FOREGROUND,##d8e3e0"
      "GUM_FILTER_CURSOR_TEXT_BACKGROUND,##0b1113"
      "GUM_FILTER_SELECTED_FOREGROUND,##f2f8f6"
      "GUM_FILTER_SELECTED_BACKGROUND,##365156"
      "GUM_FILTER_INDICATOR_FOREGROUND,##33b8a8"
      "GUM_FILTER_HEADER_FOREGROUND,##d8e3e0"
      "GUM_FILTER_MATCH_BACKGROUND,##0b1113"
      "GUM_FILTER_HEADER_BACKGROUND,##0b1113"
      "GUM_FILTER_PLACEHOLDER_FOREGROUND,##4a5f62"
      "GUM_FILTER_PLACEHOLDER_BACKGROUND,##0b1113"
      "GUM_FILTER_INDICATOR_BACKGROUND,##0b1113"
      "GUM_FILTER_SELECTED_PREFIX_FOREGROUND,##f2f8f6"
      "GUM_FILTER_SELECTED_PREFIX_BACKGROUND,##365156"
      "GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND,##4a5f62"
      "GUM_FILTER_UNSELECTED_PREFIX_BACKGROUND,##0b1113"

      # Gum Table Style
      "GUM_TABLE_HEADER_FOREGROUND,##d8e3e0"
      "GUM_TABLE_HEADER_BACKGROUND,##0b1113"
      "GUM_TABLE_CELL_FOREGROUND,##d8e3e0"
      "GUM_TABLE_CELL_BACKGROUND,##0b1113"
      "GUM_TABLE_BORDER_FOREGROUND,##4a5f62"
      "GUM_TABLE_BORDER_BACKGROUND,##0b1113"
      "GUM_TABLE_SELECTED_FOREGROUND,##f2f8f6"
      "GUM_TABLE_SELECTED_BACKGROUND,##365156"

      # Gum Spin Style
      "GUM_SPIN_SPINNER_FOREGROUND,##33b8a8"
      "GUM_SPIN_SPINNER_BACKGROUND,##0b1113"
      "GUM_SPIN_TITLE_FOREGROUND,##d8e3e0"
      "GUM_SPIN_TITLE_BACKGROUND,##0b1113"

      # Gum File Style
      "GUM_FILE_CURSOR_FOREGROUND,##d8e3e0"
      "GUM_FILE_CURSOR_BACKGROUND,##0b1113"
      "GUM_FILE_SYMLINK_FOREGROUND,##d8e3e0"
      "GUM_FILE_SYMLINK_BACKGROUND,##0b1113"
      "GUM_FILE_DIRECTORY_FOREGROUND,##d8e3e0"
      "GUM_FILE_DIRECTORY_BACKGROUND,##0b1113"
      "GUM_FILE_FILE_FOREGROUND,##d8e3e0"
      "GUM_FILE_FILE_BACKGROUND,##0b1113"
      "GUM_FILE_PERMISSIONS_FOREGROUND,##4a5f62"
      "GUM_FILE_PERMISSIONS_BACKGROUND,##0b1113"
      "GUM_FILE_SELECTED_FOREGROUND,##f2f8f6"
      "GUM_FILE_SELECTED_BACKGROUND,##365156"
      "GUM_FILE_FILE_SIZE_FOREGROUND,##4a5f62"
      "GUM_FILE_FILE_SIZE_BACKGROUND,##0b1113"
      "GUM_FILE_HEADER_FOREGROUND,##d8e3e0"
      "GUM_FILE_HEADER_BACKGROUND,##0b1113"

      # Gum Pager Style
      "GUM_PAGER_FOREGROUND,##d8e3e0"
      "GUM_PAGER_BACKGROUND,##0b1113"
      "GUM_PAGER_LINE_NUMBER_FOREGROUND,##4a5f62"
      "GUM_PAGER_LINE_NUMBER_BACKGROUND,##0b1113"
      "GUM_PAGER_MATCH_FOREGROUND,##33b8a8"
      "GUM_PAGER_MATCH_BACKGROUND,##0b1113"
      "GUM_PAGER_MATCH_HIGH_FOREGROUND,##33b8a8"
      "GUM_PAGER_MATCH_HIGH_BACKGROUND,##0b1113"
      "GUM_PAGER_HELP_FOREGROUND,##4a5f62"
      "GUM_PAGER_HELP_BACKGROUND,##0b1113"

      # Gum Write Style
      "GUM_WRITE_BASE_FOREGROUND,##d8e3e0"
      "GUM_WRITE_BASE_BACKGROUND,##0b1113"
      "GUM_WRITE_CURSOR_LINE_NUMBER_FOREGROUND,##4a5f62"
      "GUM_WRITE_CURSOR_LINE_NUMBER_BACKGROUND,##0b1113"
      "GUM_WRITE_CURSOR_LINE_FOREGROUND,##d8e3e0"
      "GUM_WRITE_CURSOR_LINE_BACKGROUND,##365156"
      "GUM_WRITE_CURSOR_FOREGROUND,##d8e3e0"
      "GUM_WRITE_CURSOR_BACKGROUND,##0b1113"
      "GUM_WRITE_END_OF_BUFFER_FOREGROUND,##4a5f62"
      "GUM_WRITE_END_OF_BUFFER_BACKGROUND,##0b1113"
      "GUM_WRITE_LINE_NUMBER_FOREGROUND,##4a5f62"
      "GUM_WRITE_LINE_NUMBER_BACKGROUND,##0b1113"
      "GUM_WRITE_HEADER_FOREGROUND,##d8e3e0"
      "GUM_WRITE_HEADER_BACKGROUND,##0b1113"
      "GUM_WRITE_PLACEHOLDER_FOREGROUND,##4a5f62"
      "GUM_WRITE_PLACEHOLDER_BACKGROUND,##0b1113"
      "GUM_WRITE_PROMPT_FOREGROUND,##d8e3e0"
      "GUM_WRITE_PROMPT_BACKGROUND,##0b1113"

      # Gum Log Style
      "GUM_LOG_LEVEL_FOREGROUND,##33b8a8"
      "GUM_LOG_LEVEL_BACKGROUND,##0b1113"
      "GUM_LOG_TIME_FOREGROUND,##4a5f62"
      "GUM_LOG_TIME_BACKGROUND,##0b1113"
      "GUM_LOG_PREFIX_FOREGROUND,##d8e3e0"
      "GUM_LOG_PREFIX_BACKGROUND,##0b1113"
      "GUM_LOG_MESSAGE_FOREGROUND,##d8e3e0"
      "GUM_LOG_MESSAGE_BACKGROUND,##0b1113"
      "GUM_LOG_KEY_FOREGROUND,##d8e3e0"
      "GUM_LOG_KEY_BACKGROUND,##0b1113"
      "GUM_LOG_VALUE_FOREGROUND,##d8e3e0"
      "GUM_LOG_VALUE_BACKGROUND,##0b1113"
      "GUM_LOG_SEPARATOR_FOREGROUND,##4a5f62"
      "GUM_LOG_SEPARATOR_BACKGROUND,##0b1113"

      # Cursor
      "XCURSOR_SIZE,24"
      "HYPRCURSOR_SIZE,24"

      # Wayland
      "GDK_BACKEND,wayland,x11,*"
      "QT_QPA_PLATFORM,wayland;xcb"
      "QT_STYLE_OVERRIDE,kvantum"
      "MOZ_ENABLE_WAYLAND,1"
      "ELECTRON_OZONE_PLATFORM_HINT,wayland"
      "OZONE_PLATFORM,wayland"
      "XDG_SESSION_TYPE,wayland"

      # Screen sharing
      "XDG_CURRENT_DESKTOP,Hyprland"
      "XDG_SESSION_DESKTOP,Hyprland"

      # XCompose
      "XCOMPOSEFILE,~/.XCompose"
    ];

    xwayland = {
      force_zero_scaling = true;
    };

    ecosystem = {
      no_update_news = true;
    };
  };
}
