{
  config,
  lib,
  ...
}:

{
  # Bootstrap the HyprMon mutable monitor sidecar ONLY if it does not exist.
  # Creates a real user-writable file (never a Nix/HM store symlink) so HyprMon
  # and leenix-monitor can edit it at runtime. An existing file is never
  # overwritten. A header-only default means `require("hyprmon")` below never
  # fails on a fresh host, while Nix's monitors.nix default governs the layout
  # until HyprMon/leenix-monitor fill the file in.
  home.activation.hyprmonBootstrap = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    hyprmon_lua="''${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprmon.lua"
    if [[ ! -f "$hyprmon_lua" ]]; then
      mkdir -p "$(dirname "$hyprmon_lua")"
      printf '%s\n\n' '-- Generated by HyprMon. Manual changes may be overwritten.' > "$hyprmon_lua"
    fi
  '';

  wayland.windowManager.hyprland = {
    enable = true;
    systemd.enable = false;
    configType = "lua";

    extraConfig = ''
      hl.config({
        misc = {
          allow_session_lock_restore = true
        }
      })

      -- HyprMon is the mutable monitor-layout owner via ~/.config/hypr/hyprmon.lua.
      -- This exact include (HyprMon's managed-include marker) is present so the
      -- HyprMon TUI detects it and never tries to write the Nix-owned (read-only)
      -- hyprland.lua. Loaded last: runtime monitor state overrides Nix defaults.
      -- hyprmon: managed monitor profile include
      require("hyprmon")
    '';
  };
}
