return {
  format_on_save = {
    lsp_format = "fallback",
    timeout_ms = 1000,
  },

  formatters_by_ft = {
    lua = { "stylua" },

    rust = { "rustfmt" },
    go = { "gofumpt", "goimports" },
    c = { "clang-format" },
    cpp = { "clang-format" },
    objc = { "clang-format" },
    objcpp = { "clang-format" },
    java = { "google-java-format" },
    haskell = { "fourmolu" },

    javascript = { "prettierd", "prettier" },
    javascriptreact = { "prettierd", "prettier" },
    typescript = { "prettierd", "prettier" },
    typescriptreact = { "prettierd", "prettier" },
    html = { "prettierd", "prettier" },
    htmx = { "prettierd", "prettier" },
    htmldjango = { "djlint" },
    jinja = { "djlint" },
    gohtml = { "djlint" },
    gohtmltmpl = { "djlint" },
    twig = { "djlint" },
    njk = { "djlint" },
    mustache = { "djlint" },
    handlebars = { "djlint" },
    hbs = { "djlint" },
    templ = { "templ" },
    css = { "prettierd", "prettier" },
    json = { "prettierd", "prettier" },
    jsonc = { "prettierd", "prettier" },
    markdown = { "prettierd", "prettier" },
    yaml = { "yamlfmt", "prettierd", "prettier" },
    yml = { "yamlfmt", "prettierd", "prettier" },
    ["yaml.docker-compose"] = { "yamlfmt", "prettierd", "prettier" },
    sql = { "sqlfluff" },
    xml = { "xmlformat" },
    python = { "ruff_format", "isort" },
  },
}
